# Generated by Django 5.2.4 on 2026-04-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descricao')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('urlImagem', models.TextField(verbose_name='Url_Imagem')),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria', verbose_name='Categoria_Id')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario', verbose_name='Usuario_Id')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produto',
                'db_table': 'produto',
                'managed': True,
            },
        ),
    ]
