# Generated by Django 5.2.4 on 2026-04-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categoria',
                'db_table': 'categoria',
                'managed': True,
            },
        ),
    ]
